runtime: python38 # or another supported version

instance_class: F1 # this is the cheapest option

env_variables:
  MYSQL_USER: root
  MYSQL_PASSWORD: sQKv-&>A>x-Q[7;^
  MYSQL_DB: 'course_app_schema'
  MYSQL_HOST: 34.122.198.36
handlers:

  - url: /script
    static_dir: static/script

  - url: /styles
    static_dir: static/styles
